# Generated by Django 2.2.5 on 2021-10-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_superhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_book_genre',
            field=models.CharField(choices=[('action', '액션'), ('sf', 'SF'), ('comedy', '코미디'), ('romance', '로맨스'), ('horror', '공포'), ('war', '전쟁'), ('sports', '스포츠'), ('fantasy', '판타지'), ('none', '없음')], default='none', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_movie_genre',
            field=models.CharField(choices=[('action', '액션'), ('sf', 'SF'), ('comedy', '코미디'), ('romance', '로맨스'), ('horror', '공포'), ('war', '전쟁'), ('sports', '스포츠'), ('fantasy', '판타지'), ('none', '없음')], default='none', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('book', '책'), ('movie', '영화'), ('all', '모두'), ('none', '없음')], default='none', max_length=5),
        ),
    ]
