# Generated by Django 2.2.5 on 2021-10-14 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=140, null=True)),
                ('description', models.TextField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=140, null=True)),
                ('guests', models.IntegerField(null=True)),
                ('beds', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('baths', models.IntegerField(null=True)),
                ('check_in', models.TimeField(default='')),
                ('check_out', models.TimeField(default='')),
                ('instant_book', models.BooleanField(default=False)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
